{include file='admin/library/header'}
<table width="100%" class="table table-striped">
	<tr>
		<th>序号</th><th>标题</th><th>内容</th><th>更新时间</th><th>状态</th><th>操作</th>
	</tr>
	{foreach from=$result.data key=key item=item}
	<tr> 
		<td>{$item.bid}</td> 
		<td>{$item.title}</td> 
		<td>{$item.content}</td> 
		<td>{$item.updated}</td> 
		<td>{$item.status}</td> 
		<td><a href="/admin/blog&ac=add&bid={$item.bid}">修改</a><a href="javascript:;" class="J_del" val="{$item.bid}">删除</a></td>
	</tr>
	{/foreach}
</table>
{$result.page}

<script>
	$(document).ready(function(){
		$(".J_del").click(function(){
			var _bid = $(this).attr("val");

			if (!confirm('确定要删除？'))return;
			$.ajax({
				url: "/admin/blog/&ac=del",
				data: "bid="+_bid,
				dataType: "json",
				type: "POST",
				error: function(){
					alert('异常，删除失败！');
				},
				success: function(data){
					if (data.code == 200) {
						javacript:location.reload();
						} else {
						alert('删除失败！');
					}
				}
			});
		});
	});
</script>
{include file='admin/library/footer'}
