<!DOCTYPE html>
<html>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<head>
		<title></title>
	</head>
	<body>
		<div>
			<form action="login" method="post" />
				<div>
					<label>用户名：</label><input type="text" name="username" />
				</div>
				<div>
					<label>密码：</label><input type="password" name="password" />
				</div>
				<div>
					<input type="submit" value="登录" />
				</div>
			</form>
		</div>
	</body>
</html>
